platform :ios,'7.0'
pod 'Facebook-iOS-SDK', :inhibit_warnings => true
pod 'GCPlaceholderTextView'
pod 'Mixpanel'
pod 'MBProgressHUD'
pod 'FormatterKit'
pod 'MGImageUtilities'
pod 'Google-Mobile-Ads-SDK'
pod 'iRate'
pod 'CTFeedback'
pod 'GoogleAnalytics-iOS-SDK', '3.0.3'
pod 'UIActionSheet+Blocks'